In [9]:
import sqlite3
import pandas as pd
import re
import os

print("Sab kuch sahi chal raha hai ✅")

Sab kuch sahi chal raha hai ✅

In [11]:
print(os.getcwd())

c:\Users\Hp\OneDrive\Desktop\PROJECT DATA ANALYST

In [12]:
print(os.listdir())

['daily_exchange_rates.csv', 'enterprise_database.db', 'project.ipynb', 'server_logs.txt']

In [13]:
conn = sqlite3.connect("enterprise_database.db")

print("Database Connected Successfully ✅")

Database Connected Successfully ✅

In [14]:
query = "SELECT name FROM sqlite_master WHERE type='table';"

tables = pd.read_sql(query, conn)

tables

    name
0  users

In [16]:
query = "SELECT name FROM sqlite_master WHERE type='table';"

tables = pd.read_sql(query, conn)

print(tables)

    name
0  users

In [18]:
import os

print(os.listdir())

['daily_exchange_rates.csv', 'enterprise_database.db', 'project.ipynb', 'server_logs.txt']

In [20]:
query = "SELECT * FROM users LIMIT 10;"

df = pd.read_sql(query, conn)

df

   user_id          name     status           updated_at
0  U-00000  User_U-00000    Pending  2023-01-01 10:00:00
1  U-00000  User_U-00000     Active  2023-01-19 14:00:00
2  U-00000  User_U-00000  Suspended  2023-02-28 09:00:00
3  U-00001  User_U-00001    Pending  2023-01-01 10:00:00
4  U-00001  User_U-00001     Active  2023-01-28 14:00:00
5  U-00002  User_U-00002    Pending  2023-01-01 10:00:00
6  U-00002  User_U-00002     Active  2023-01-29 14:00:00
7  U-00002  User_U-00002  Suspended  2023-02-23 09:00:00
8  U-00003  User_U-00003    Pending  2023-01-01 10:00:00
9  U-00003  User_U-00003     Active  2023-01-22 14:00:00

In [21]:
query = """
SELECT u.*
FROM users u
JOIN (
    SELECT user_id, MAX(updated_at) AS latest_time
    FROM users
    GROUP BY user_id
) latest
ON u.user_id = latest.user_id
AND u.updated_at = latest.latest_time
WHERE u.status = 'Active';
"""

active_users = pd.read_sql(query, conn)

active_users

       user_id          name  status           updated_at
0      U-00001  User_U-00001  Active  2023-01-28 14:00:00
1      U-00003  User_U-00003  Active  2023-01-22 14:00:00
2      U-00005  User_U-00005  Active  2023-01-17 14:00:00
3      U-00006  User_U-00006  Active  2023-01-05 14:00:00
4      U-00007  User_U-00007  Active  2023-01-27 14:00:00
...        ...           ...     ...                  ...
14178  U-24989  User_U-24989  Active  2023-01-22 14:00:00
14179  U-24991  User_U-24991  Active  2023-01-08 14:00:00
14180  U-24992  User_U-24992  Active  2023-01-16 14:00:00
14181  U-24995  User_U-24995  Active  2023-01-06 14:00:00
14182  U-24996  User_U-24996  Active  2023-01-20 14:00:00

[14183 rows x 4 columns]

In [22]:
print("Total Active Users:", len(active_users))

Total Active Users: 14183

In [24]:
with open("server_logs.txt", "r") as file:
    for i in range(5):
        print(file.readline())

Raw_Server_Log

"[2023-03-15 00:00:00] INFO: Transaction processed. payload={""u"":""U-19484"", ""item_code"":""PRD-874"", ""eur_val"":3404.44}"

"[2023-09-09 00:00:00] ERROR: Transaction processed. payload={""u"":""U-21438"", ""item_code"":""PRD-793"", ""failed_val"":41.24}"

"[2023-05-09 00:00:00] INFO: Transaction processed. payload={""u"":""U-18932"", ""item_code"":""PRD-905"", ""eur_val"":3406.21}"

"[2023-10-21 00:00:00] INFO: Transaction processed. payload={""u"":""U-15882"", ""item_code"":""PRD-284"", ""eur_val"":164.08}"

In [25]:
import re

with open("server_logs.txt", "r") as file:
    text = file.read()

pattern = r'\[(.*?)\].*?INFO.*?"u":"(.*?)".*?"item_code":"(.*?)".*?"eur_val":([0-9.]+)'

matches = re.findall(pattern, text)

print(matches[:5])

[]

In [26]:
logs_df = pd.DataFrame(
    matches,
    columns=[
        "date",
        "user_id",
        "product_id",
        "eur_value"
    ]
)

logs_df.head()

Empty DataFrame
Columns: [date, user_id, product_id, eur_value]
Index: []

In [27]:
print(logs_df.shape)

(0, 4)

In [28]:
with open("server_logs.txt", "r", encoding="utf-8") as file:
    text = file.read()

print(text[:500])

Raw_Server_Log
"[2023-03-15 00:00:00] INFO: Transaction processed. payload={""u"":""U-19484"", ""item_code"":""PRD-874"", ""eur_val"":3404.44}"
"[2023-09-09 00:00:00] ERROR: Transaction processed. payload={""u"":""U-21438"", ""item_code"":""PRD-793"", ""failed_val"":41.24}"
"[2023-05-09 00:00:00] INFO: Transaction processed. payload={""u"":""U-18932"", ""item_code"":""PRD-905"", ""eur_val"":3406.21}"
"[2023-10-21 00:00:00] INFO: Transaction processed. payload={""u"":""U-15882"", ""item_code"":""

In [29]:
logs = pd.read_csv("server_logs.txt")

logs.head()

                                      Raw_Server_Log
0  [2023-03-15 00:00:00] INFO: Transaction proces...
1  [2023-09-09 00:00:00] ERROR: Transaction proce...
2  [2023-05-09 00:00:00] INFO: Transaction proces...
3  [2023-10-21 00:00:00] INFO: Transaction proces...
4  [2023-01-10 00:00:00] INFO: Transaction proces...

In [30]:
print(logs.columns)
print(logs.shape)

Index(['Raw_Server_Log'], dtype='str')
(100000, 1)

In [31]:
print(logs["Raw_Server_Log"].iloc[0])

[2023-03-15 00:00:00] INFO: Transaction processed. payload={"u":"U-19484", "item_code":"PRD-874", "eur_val":3404.44}

In [32]:
import re

sample = '[2023-03-15 00:00:00] INFO: Transaction processed. payload={"u":"U-19484", "item_code":"PRD-874", "eur_val":3404.44}'

pattern = r'\[(.*?)\].*?INFO.*?"u":"(.*?)".*?"item_code":"(.*?)".*?"eur_val":([0-9.]+)'

match = re.search(pattern, sample)

print(match.groups())

('2023-03-15 00:00:00', 'U-19484', 'PRD-874', '3404.44')

In [33]:
import pandas as pd
import re

logs = pd.read_csv("server_logs.txt")

pattern = r'\[(.*?)\].*?INFO.*?"u":"(.*?)".*?"item_code":"(.*?)".*?"eur_val":([0-9.]+)'

data = []

for line in logs["Raw_Server_Log"]:
    match = re.search(pattern, str(line))
    if match:
        data.append(match.groups())

logs_df = pd.DataFrame(
    data,
    columns=["date", "user_id", "product_id", "eur_value"]
)

logs_df.head()

                  date  user_id product_id eur_value
0  2023-03-15 00:00:00  U-19484    PRD-874   3404.44
1  2023-05-09 00:00:00  U-18932    PRD-905   3406.21
2  2023-10-21 00:00:00  U-15882    PRD-284    164.08
3  2023-01-10 00:00:00  U-22781    PRD-665      26.8
4  2023-05-23 00:00:00  U-13348    PRD-589   4964.77

In [34]:
rates = pd.read_csv("daily_exchange_rates.csv")

rates.head()

         Date  EUR_to_USD
0  2023-01-01    1.124836
1  2023-01-02    1.093087
2  2023-01-03    1.132384
3  2023-01-04    1.176151
4  2023-01-05    1.088292

In [35]:
print(rates.columns)

Index(['Date', 'EUR_to_USD'], dtype='str')

In [36]:
logs_df["date"] = pd.to_datetime(logs_df["date"]).dt.date
rates["Date"] = pd.to_datetime(rates["Date"]).dt.date

In [37]:
merged_df = pd.merge(
    logs_df,
    rates,
    left_on="date",
    right_on="Date",
    how="left"
)

merged_df.head()

         date  user_id product_id eur_value        Date  EUR_to_USD
0  2023-03-15  U-19484    PRD-874   3404.44  2023-03-15    1.178232
1  2023-05-09  U-18932    PRD-905   3406.21  2023-05-09    1.104983
2  2023-10-21  U-15882    PRD-284    164.08  2023-10-21         NaN
3  2023-01-10  U-22781    PRD-665      26.8  2023-01-10    1.127128
4  2023-05-23  U-13348    PRD-589   4964.77  2023-05-23    1.019626

In [38]:
final_df = merged_df[
    [
        "date",
        "user_id",
        "product_id",
        "eur_value",
        "EUR_to_USD",
        "usd_value"
    ]
]

final_df.head()

KeyError: "['usd_value'] not in index"

In [39]:
print(merged_df.columns)

Index(['date', 'user_id', 'product_id', 'eur_value', 'Date', 'EUR_to_USD'], dtype='str')

In [40]:
merged_df["eur_value"] = merged_df["eur_value"].astype(float)

merged_df["usd_value"] = merged_df["eur_value"] * merged_df["EUR_to_USD"]

merged_df.head()

,date,user_id,product_id,eur_value,Date,EUR_to_USD,usd_value
0,2023-03-15,U-19484,PRD-874,3404.44,2023-03-15,1.178232,4011.220772
1,2023-05-09,U-18932,PRD-905,3406.21,2023-05-09,1.104983,3763.802674
2,2023-10-21,U-15882,PRD-284,164.08,2023-10-21,NaN,NaN
3,2023-01-10,U-22781,PRD-665,26.80,2023-01-10,1.127128,30.207030
4,2023-05-23,U-13348,PRD-589,4964.77,2023-05-23,1.019626,5062.207773

In [41]:
print(merged_df.columns)

Index(['date', 'user_id', 'product_id', 'eur_value', 'Date', 'EUR_to_USD',
       'usd_value'],
      dtype='str')

In [42]:
final_df = merged_df[
    [
        "date",
        "user_id",
        "product_id",
        "eur_value",
        "EUR_to_USD",
        "usd_value"
    ]
]

final_df.head()

         date  user_id product_id  eur_value  EUR_to_USD    usd_value
0  2023-03-15  U-19484    PRD-874    3404.44    1.178232  4011.220772
1  2023-05-09  U-18932    PRD-905    3406.21    1.104983  3763.802674
2  2023-10-21  U-15882    PRD-284     164.08         NaN          NaN
3  2023-01-10  U-22781    PRD-665      26.80    1.127128    30.207030
4  2023-05-23  U-13348    PRD-589    4964.77    1.019626  5062.207773

In [43]:
merged_df["eur_value"] = merged_df["eur_value"].astype(float)
merged_df["usd_value"] = merged_df["eur_value"] * merged_df["EUR_to_USD"]
print(merged_df.columns)

Index(['date', 'user_id', 'product_id', 'eur_value', 'Date', 'EUR_to_USD',
       'usd_value'],
      dtype='str')

In [44]:
final_df = merged_df[
    [
        "date",
        "user_id",
        "product_id",
        "eur_value",
        "EUR_to_USD",
        "usd_value"
    ]
]

final_df.head()

         date  user_id product_id  eur_value  EUR_to_USD    usd_value
0  2023-03-15  U-19484    PRD-874    3404.44    1.178232  4011.220772
1  2023-05-09  U-18932    PRD-905    3406.21    1.104983  3763.802674
2  2023-10-21  U-15882    PRD-284     164.08         NaN          NaN
3  2023-01-10  U-22781    PRD-665      26.80    1.127128    30.207030
4  2023-05-23  U-13348    PRD-589    4964.77    1.019626  5062.207773

In [45]:
print(final_df.shape)

(94902, 6)

In [46]:
final_df.to_csv("final_report.csv", index=False)

print("✅ final_report.csv successfully created")

✅ final_report.csv successfully created

In [47]:
import os

print(os.listdir())

['daily_exchange_rates.csv', 'enterprise_database.db', 'final_report.csv', 'project.ipynb', 'server_logs.txt']

In [48]:
final_df = final_df.dropna()

In [49]:
print(final_df.shape)

(67918, 6)

In [50]:
final_df.to_csv("final_report.csv", index=False)